name: update-dev-environment
on:
  repository_dispatch:
    types: [update-dev-environment]
  push:
    branches:
      - "master"
    paths:
      - envs/base/**
      - envs/development/**

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Dev SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEV_HOST }}
          username: ${{ secrets.DEV_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /datadrive/data/interlink-project
            git pull --ff-only
            cd envs/development
            docker-compose pull
            docker-compose up -d
            docker-compose exec -T catalogue python /app/app/pre_start.py
            docker-compose exec -T coproduction python /app/app/pre_start.py
            docker-compose exec -T catalogue python /app/app/initial_data.py
            docker-compose exec -T coproduction python /app/app/initial_data.py